repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [push]
        language: system
        entry: poetry run isort
        types: [python]
        exclude: tmp.py

      - id: black
        name: black
        stages: [push]
        language: system
        entry: poetry run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [push]
        language: system
        entry: poetry run flake8
        types: [python]
        exclude: tmp.py

      - id: mypy
        name: mypy
        stages: [push]
        language: system
        entry: poetry run mypy
        types: [python]
        pass_filenames: false
        exclude: tmp.py

      - id: pytest
        name: pytest
        stages: [push]
        language: system
        entry: poetry run pytest
        always_run: false
        types: [python]
        exclude: tmp.py

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: poetry run pytest --cov --cov-fail-under=100
        types: [python]
        pass_filenames: false
        exclude: tmp.py
