version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: Install PDM
          command: |
            curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -
            pdm -V
      - run:
          name: Install dependencies
          command: pdm install
      - run:
          name: Test
          command: pdm run pytest
      - run:
          name: Lint
          command: pdm run flake8
      - run:
          name: Check types
          command: pdm run mypy
workflows:
  build-and-test:
    jobs:
      - build-and-test
