version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install the latest version of Poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_UNINSTALL=1 python -
            curl -sSL https://install.python-poetry.org | python3 -
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: pytest
workflows:
  build-and-test:
    jobs:
      - build-and-test
