version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: Uninstall old Poetry and install the latest version of Poetry
          command: |
            poetry --version
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/901bdf0491005f1b3db41947d0d938da6838ecb9/get-poetry.py | python3 - --uninstall
            curl -sSL https://install.python-poetry.org | python3 -
            echo 'export PATH="/home/circleci/.local/bin:${PATH}"' >> ${BASH_ENV}
            source ${BASH_ENV}
            poetry --version
            poetry install
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest
workflows:
  build-and-test:
    jobs:
      - build-and-test
