version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: Uninstall old Poetry and install the latest version of Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 - --uninstall
            curl -sSL https://install.python-poetry.org | python3 -
            poetry --version
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest
workflows:
  build-and-test:
    jobs:
      - build-and-test
